nosmoking/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^nosmoking/', include('polls.urls',
                                                   namespace='polls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<poll_id>\d+)/answer/(?P<user_uuid>.+)/$',
                           views.answer, name='answer'),
                       url(r'^(?P<poll_id>\d+)/sign/(?P<user_uuid>.+)/$',
                           views.sign, name='sign'),
                       url(r'^(?P<poll_id>\d+)/thanks/(?P<user_uuid>.+)/$',
                           views.thanks, name='thanks'),                       
                       url(r'^(?P<poll_id>\d+)/(?P<user_uuid>.+)/$',
                           views.detail, name='detail'),                       
)

polls/models.py
from django.db import models

from django.contrib.auth.models import User

import random
import string

import base64

random.seed()

class Poll(models.Model):
    subject = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.subject
    
class Question(models.Model):
    poll = models.ForeignKey(Poll)
    question_text = models.CharField(max_length=200)
    position = models.IntegerField(default=0)    

    def __unicode__(self):
        return self.question_text

    class Meta:
        ordering = ['position']
    
class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    position = models.IntegerField(default=0)    

    def __unicode__(self):
        return self.choice_text

    class Meta:
        ordering = ['position']

class Institution(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __unicode__(self):
        return self.name

class School(models.Model):
    name = models.CharField(max_length=100, unique=True)

class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)
        
class Participant(models.Model):
    poll = models.ForeignKey(Poll)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=60)
    institution = models.ForeignKey(Institution)
    school = models.ForeignKey(School, null=True)
    department = models.ForeignKey(Department)
    unique_id = models.CharField(max_length=100, unique=True)
    completed = models.BooleanField(default=False)

    @classmethod
    def generate_unique_id(cls):
        unique_id = ''.join(random.choice(string.ascii_lowercase +
                                          string.digits)
                            for x in range(20))
        while Participant.objects.filter(unique_id=unique_id).exists():
            unique_id = ''.join(random.choice(string.ascii_lowercase +
                                              string.digits)
                                for x in range(50))
        return unique_id

    def get_response(self, choice):
        related = Response.objects.select_related('choice__question')
        filtered = filter(participant=self,
                          choice__question=choice.question)
        
class Response(models.Model):
    participant = models.ForeignKey(Participant)
    choice = models.ForeignKey(Choice)
    created_at = models.DateTimeField(auto_now_add=True)    
    modified_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return (self.participant.email
                + " "
                + self.choice.question.question_text
                + " "
                + self.choice.choice_text)

class Sign(models.Model):
    participant = models.ForeignKey(Participant)
    agree = models.NullBooleanField()
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    institution = models.ForeignKey(Institution)
    created_at = models.DateTimeField(auto_now_add=True)    
    modified_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return (self.participant.email
                + " "
                + str((self.agree or "")))


class Attachment(models.Model):
    filename = models.CharField(max_length=100)
    mimetype = models.CharField(max_length=100)
    _data = models.TextField(db_column='data', blank=True)
    
    def set_data(self, data):
        self._data = base64.encodestring(data)

    def get_data(self):
        return base64.decodestring(self._data)

    data = property(get_data, set_data)

class EmailMessage(models.Model):
    poll = models.ForeignKey(Poll)
    title = models.CharField(max_length=100, unique=True)
    from_header = models.CharField(max_length=100)
    subject_header = models.CharField(max_length=100)
    body = models.TextField()
    attachments = models.ManyToManyField(Attachment,
                                         db_table='polls_message_attachment')

    def __unicode__(self):
        return self.title
    
class Notification(models.Model):
    participant = models.ForeignKey(Participant)
    email_message = models.ForeignKey(EmailMessage)
    created_at = models.DateTimeField(auto_now_add=True)

polls/forms.py
from django import forms
from django.forms.widgets import RadioSelect

class DetailForm(forms.Form):

    def __init__(self, *args, **kwargs):
        questions = kwargs.pop('questions')
        super(DetailForm, self).__init__(*args, **kwargs)
         
        for i, question in enumerate(questions):
            question_label = question.question_text
            question_choices = [(c.id, c.choice_text)
                                for c in question.choice_set.all()]
            self.fields['question_%s' % i] = forms.ChoiceField(
                label=question_label,
                choices=question_choices,
                widget=RadioSelect)

    def answers(self):
        for name, value in self.cleaned_data.items():
            if name.startswith('question_'):
                yield (value)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect

from django.shortcuts import render, get_object_or_404, redirect

from django.core.urlresolvers import reverse

from models import Poll, Institution, Participant, Response, Sign

from forms import DetailForm

SHOW_SIGNATURES_COUNT_LIMIT = 1000

def index(request):
    latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]
    context = {'latest_poll_list': latest_poll_list}
    return render(request, 'polls/index.html', context)

def detail(request, poll_id, user_uuid):
    poll = get_object_or_404(Poll, pk=poll_id)
    participant = get_object_or_404(Participant, unique_id=user_uuid)
    if participant.completed:
        return redirect(reverse('polls:thanks',
                                args=(poll.id,
                                      user_uuid,)))     
    questions = poll.question_set.all()
    form = DetailForm(questions=questions)
    return render(request, 'polls/detail.html',
                  {
                      'poll': poll,
                      'user_uuid': user_uuid,
                      'form': form,
                  })

def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})    

def sign(request, poll_id, user_uuid):
    poll = get_object_or_404(Poll, pk=poll_id)
    participant = get_object_or_404(Participant, unique_id=user_uuid)
    if participant.completed:
        return redirect(reverse('polls:thanks',
                                args=(poll.id,
                                      user_uuid,)))     
    institution_list = Institution.objects.all().order_by('name')
    if request.method == 'POST':
        participant.completed = True
        to_delete = Sign.objects.filter(participant=participant)
        to_delete.delete()        
        sign = Sign()
        sign.participant = participant
        if 'first-name' in request.POST:
            sign.first_name = request.POST['first-name']
        if 'last-name' in request.POST:
            sign.last_name = request.POST['last-name']
        if 'sign-agree' in request.POST:
            sign.agree = True
        if 'sign-disagree' in request.POST:
            sign.agree = False
        if 'sign-no-opinion' in request.POST:
            sign.agree = None
        if 'institution-id' in request.POST:
            institution_id = request.POST['institution-id']
            institution = get_object_or_404(Institution,
                                            pk=institution_id)
            sign.institution = institution
        sign.save()
        participant.save()
        return HttpResponseRedirect(reverse('polls:thanks',
                                            args=(poll.id,
                                                  user_uuid,)))
    return render(request, 'polls/sign.html',
                  {                      
                      'poll': poll,
                      'user_uuid': user_uuid,
                      'institution_list': institution_list,
                  })

def thanks(request, poll_id, user_uuid):
    participant = get_object_or_404(Participant, unique_id=user_uuid)
    signature_count = Sign.objects.all().count()
    show_signature_count =  signature_count > SHOW_SIGNATURES_COUNT_LIMIT
    return render(request, 'polls/thanks.html',                  
                  {
                      'show_signature_count': show_signature_count,
                      'signature_count': signature_count,
                  })

def answer(request, poll_id, user_uuid):
    poll = get_object_or_404(Poll, pk=poll_id)
    participant = get_object_or_404(Participant, unique_id=user_uuid)
    if participant.completed:
        return redirect(reverse('polls:thanks',
                                args=(poll.id,
                                      user_uuid,))) 
    questions = poll.question_set.all()
    if request.method == 'POST':
        form = DetailForm(request.POST, questions=questions)
        if form.is_valid():
            to_delete = Response.objects.filter(participant=participant)
            to_delete.delete()
            for choice_id in form.answers():
                response = Response(participant=participant,
                                    choice_id=choice_id)
                response.save()
            return HttpResponseRedirect(reverse('polls:sign',
                                                args=(poll.id,
                                                      user_uuid,)))
    else:
        form = DetailForm(questions=questions)
    return render(request, 'polls/detail.html',
                  {
                      'poll': poll,
                      'form': form,
                      'user_uuid': user_uuid,
                  })

polls/templates/polls/base.html
<!DOCTYPE html>
<html>
{% block head %}
<head>
  {% load staticfiles %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static "polls/css/bootstrap.min.css" %}"
        media="screen"/>
  <link rel="stylesheet"
        href="{% static "polls/css/bootstrap-responsive.min.css" %}"/>        
  <link rel="stylesheet" href="{% static "polls/css/nosmoking.css" %}"
         media="screen"/>
  <title>{% block title %}No Smoking Survey{% endblock %}</title>
  <style>
    </style>
</head>
{% endblock %}

<body>
  {% block main %}
  <div id="wrap">
    <div class="container" id="content">
      {% block content %}
      {% endblock %}
    </div>
    <div id="push"></div>
  </div>
  {% endblock main %}
  
  <div id="footer">
    <div class="container">
      <p class="muted credit">
        Greek Research and Technology Network
        <a href="http://www.grnet.gr">(GRNET)</a>. Code at
        <a href="https://github.com/grnet/nosmoking/">Github</a>.
      </p>
    </div>
    
  <script src="{% static "polls/js/jquery-1.9.1.min.js" %}"></script>
  <script src="{% static "polls/js/bootstrap.min.js" %}"></script>
  <script src="{% static "polls/js/polls.js" %}?r=1"></script>
</body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block content %}
<h1>{{ poll.subject }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:answer' poll.id user_uuid %}" method="post">
{% csrf_token %}
  <fieldset>
    <legend>Παρακαλούμε απαντήστε στις παρακάτω ερωτήσεις. Οι
    απαντήσεις σας θα παραμείνουν ανώνυμες.
    </legend>
    {% for field in form %}
      <label>{{ field.label }}</label>
      {% for choice in field %}
        {{ choice }}
      {% endfor %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">Υποβολή</button>
  </fieldset>
</form>

{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li>
          <a href="{% url 'polls:detail' poll.id 0 %}">
            {{ poll.subject }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

polls/templates/polls/sign.html
{% extends "polls/base.html" %}

{% load staticfiles %}

{% block content %}
<h1>{{ poll.subject }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:sign' poll.id user_uuid %}" method="post">
{% csrf_token %}
  <fieldset>
    <legend>
      Επιθυμείτε να προσυπογράψετε το παρακάτω κείμενο, που συντάχθηκε
      από την Εθνική Επιτροπή για τον Έλεγχο του Καπνίσματος;
    </legend>

    <blockquote class="declaration">
      <p>
        Το παθητικό κάπνισμα στους κλειστούς δημόσιους χώρους είναι μια
        εκτεταμένη μορφή βίας, που στρέφεται κυρίως εναντίον μικρών
        παιδιών και αδύναμων πληθυσμιακών ομάδων, όπως είναι οι πάσχοντες
        από αναπνευστικά ή καρδιαγγειακά νοσήματα.
      </p>
      <p>
        Ιδιαίτερο είναι το πρόβλημα των εγκύων γυναικών και των
        εργαζομένων στους χώρους αυτούς, που χωρίς δυνατότητες άμυνας
        υποβάλλονται σε υποχρεωτικό κάπνισμα και υφίστανται βαριές
        συνέπειες σε ατομικό, οικογενειακό και κοινωνικό επίπεδο.
      </p>
      <p>
        Η κατάσταση στην Ελλάδα εμφανίζεται ανεξέλεγκτη, καθώς οι
        νόμοι του ίδιου μας του κράτους
        (<a href="{% static "polls/pdf/3730.pdf" %}">Ν. 3730/08</a>
        και
        <a href="{% static "polls/pdf/3868.pdf" %}">Ν.3868/10</a>) δεν
        εφαρμόζονται, και οι Διεθνείς Συμφωνίες (
        <a href="http://www.who.int/fctc/cop/art%208%20guidelines_english.pdf">
          World Health Organisation, Framework Convention on Tobacco
          Control, Article 8, Guidelines on Protection from Exposure
          to Tobacco Smoke</a>) καταπατούνται, προκειμένου να μη
          θιγούν συγκεκριμένα οικονομικά συμφέροντα.
      </p>
      <p>
        <strong>
          Εμείς, ως ακαδημαϊκοί πολίτες της χώρας αυτής, παρεμβαίνουμε
          αποφασιστικά και ζητούμε από την Ευρωπαϊκή Επιτροπή και από το
          <a href="http://www.ensp.org/">European Network for Smoking
          and Tobacco Prevention (ENSP)</a> την ανάληψη πρωτοβουλίας
          προς κάθε κατεύθυνση, για την ανάδειξη και επίσημη αναγνώριση
          του παθητικού καπνίσματος ως μείζονος παγκόσμιου θέματος
          παραβίασης ανθρωπίνων δικαιωμάτων υγείας, εργασίας και
          προστασίας της γυναίκας και του παιδιού.
        </strong>
      </p>
    </blockquote>

    <div id="sign-modal" class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
                aria-hidden="true">&times;</button>
                <h3>Συμφωνώ</h3>
      </div>
      <div class="modal-body">
        <div class="control-group">
          <input type="text" class="input-small"
                 name="first-name"
                 placeholder="Όνομα">
          <input type="text" class="input-small"
                 name="last-name"
                 placeholder="Επώνυμο">
          <select name="institution-id">
            {% for institution in institution_list %}
            <option value="{{ institution.id }}">{{ institution.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="modal-footer">
        <a href="#" data-dismiss="modal" class="btn">Ακύρωση</a>
        <button type="submit"
                name="sign-agree"
                class="btn btn-primary">ΟΚ</a>
      </div>
    </div>    
    <button type="submit"
            class="btn btn-primary"
            data-toggle="modal"
            data-target="#sign-modal">Συμφωνώ</button>
    <button type="submit" name="sign-disagree"
            class="btn-warning">Διαφωνώ</button>
    <button type="submit"
            name="sign-no-opinion"
            class="btn">Δεν έχω άποψη</button>    
  </fieldset>
</form>

{% endblock %}

polls/templates/polls/thanks.html
{% extends "polls/base.html" %}

{% block content %}

<p class="lead">Ευχαριστούμε για τη συμμετοχή σας.</p>
{% if show_signature_count %}
  Μέχρι αυτή
  τη στιγμή έχουμε {{ signature_count }} συμμετοχές στην έρευνα.
{% endif %}
</p>
  
{% endblock %}